package com.eventloop.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Commercial Quotation Package generated by AI for Private Event Management Companies.
 * (Weddings, Corporate Product Launches, Concerts, Gala Dinners, Trade Expos).
 */
public class EventQuotationPackage {
    private String packageTier; // PLATINUM_VIP, GOLD_BALANCED, SILVER_VALUE
    private String packageName; // e.g. "Platinum Royal VIP Package"
    private double clientQuotePrice; // Price charged to client
    private double internalDirectCost; // Company internal cost (in-house + cross-hire + crew)
    private double grossProfit; // Quote - Cost
    private double profitMarginPct; // e.g. 42.5%
    private double securityDepositRequired; // Refundable deposit
    private int inHouseItemsUsed;
    private int vendorCrossHiredItems;
    private int crewTechniciansNeeded;
    private int setupDurationHours;
    private String clientTargetSuitability; // e.g. "Best for Luxury Destination Weddings & High-Profile Brands"
    private List<PackageItemDetail> itemizedList = new ArrayList<>();

    public static class PackageItemDetail {
        private String category; // Sound, Stage/Truss, Ambient Lighting, Decor/Floral, LED Video Wall
        private String itemName;
        private int quantity;
        private String sourcingType; // IN_HOUSE_STOCK, VENDOR_CROSS_HIRE, SUBCONTRACT_CREW
        private double internalCost;
        private double clientBillingRate;
        private String partnerVendor; // e.g. "AudioPro Rentals", "In-House Warehouse"

        public PackageItemDetail() {}

        public PackageItemDetail(String category, String itemName, int quantity, String sourcingType, double internalCost, double clientBillingRate, String partnerVendor) {
            this.category = category;
            this.itemName = itemName;
            this.quantity = quantity;
            this.sourcingType = sourcingType;
            this.internalCost = internalCost;
            this.clientBillingRate = clientBillingRate;
            this.partnerVendor = partnerVendor;
        }

        public String getCategory() { return category; }
        public void setCategory(String category) { this.category = category; }
        public String getItemName() { return itemName; }
        public void setItemName(String itemName) { this.itemName = itemName; }
        public int getQuantity() { return quantity; }
        public void setQuantity(int quantity) { this.quantity = quantity; }
        public String getSourcingType() { return sourcingType; }
        public void setSourcingType(String sourcingType) { this.sourcingType = sourcingType; }
        public double getInternalCost() { return internalCost; }
        public void setInternalCost(double internalCost) { this.internalCost = internalCost; }
        public double getClientBillingRate() { return clientBillingRate; }
        public void setClientBillingRate(double clientBillingRate) { this.clientBillingRate = clientBillingRate; }
        public String getPartnerVendor() { return partnerVendor; }
        public void setPartnerVendor(String partnerVendor) { this.partnerVendor = partnerVendor; }
    }

    public EventQuotationPackage() {}

    public String getPackageTier() { return packageTier; }
    public void setPackageTier(String packageTier) { this.packageTier = packageTier; }
    public String getPackageName() { return packageName; }
    public void setPackageName(String packageName) { this.packageName = packageName; }
    public double getClientQuotePrice() { return clientQuotePrice; }
    public void setClientQuotePrice(double clientQuotePrice) { this.clientQuotePrice = clientQuotePrice; }
    public double getInternalDirectCost() { return internalDirectCost; }
    public void setInternalDirectCost(double internalDirectCost) { this.internalDirectCost = internalDirectCost; }
    public double getGrossProfit() { return grossProfit; }
    public void setGrossProfit(double grossProfit) { this.grossProfit = grossProfit; }
    public double getProfitMarginPct() { return profitMarginPct; }
    public void setProfitMarginPct(double profitMarginPct) { this.profitMarginPct = profitMarginPct; }
    public double getSecurityDepositRequired() { return securityDepositRequired; }
    public void setSecurityDepositRequired(double securityDepositRequired) { this.securityDepositRequired = securityDepositRequired; }
    public int getInHouseItemsUsed() { return inHouseItemsUsed; }
    public void setInHouseItemsUsed(int inHouseItemsUsed) { this.inHouseItemsUsed = inHouseItemsUsed; }
    public int getVendorCrossHiredItems() { return vendorCrossHiredItems; }
    public void setVendorCrossHiredItems(int vendorCrossHiredItems) { this.vendorCrossHiredItems = vendorCrossHiredItems; }
    public int getCrewTechniciansNeeded() { return crewTechniciansNeeded; }
    public void setCrewTechniciansNeeded(int crewTechniciansNeeded) { this.crewTechniciansNeeded = crewTechniciansNeeded; }
    public int getSetupDurationHours() { return setupDurationHours; }
    public void setSetupDurationHours(int setupDurationHours) { this.setupDurationHours = setupDurationHours; }
    public String getClientTargetSuitability() { return clientTargetSuitability; }
    public void setClientTargetSuitability(String clientTargetSuitability) { this.clientTargetSuitability = clientTargetSuitability; }
    public List<PackageItemDetail> getItemizedList() { return itemizedList; }
    public void setItemizedList(List<PackageItemDetail> itemizedList) { this.itemizedList = itemizedList; }
}
